const express = require("express")
const aboutUsRouter = require("./aboutUsRouter")
const achievementRouter = require("./achievementRouter")
const blogRouter = require("./blogRouter")
const contactUsRouter = require("./contactUsRouter")
const customerRouter = require("./customerRouter")
const faqRouter = require("./faqRouter")
const heroSectionRouter = require("./heroSectionRouter")
const processRouter = require("./processRouter")
const purposeRouter = require("./purposeRouter")
const serviceRouter = require("./serviceRouter")
const teamRouter = require("./teamRouter")
const userRouter = require("./userRouter")
const visionMissionRouter = require("./visionMissionRouter")
const ideasRouter = require("./ideasRouter")
const bottomRouter = require("./bottomRouter")
const partnerRouter = require("./partnerRouter")
const contentPricingRouter = require("./contentPricingRouter")
const topRouter = require("./topRouter")
const serviceProcessRouter = require("./serviceProcessRouter")
const specializationRouter = require("./specializationRouter")
const bookingRouter = require("./bookingRouter")
const Router = express()

Router.use("/about-us",aboutUsRouter)
Router.use("/achievement",achievementRouter)
Router.use("/blog",blogRouter)
Router.use("/contact-us",contactUsRouter)
Router.use("/customer",customerRouter)
Router.use("/faq",faqRouter)
Router.use("/hero-section",heroSectionRouter)
Router.use("/process",processRouter)
Router.use("/purpose",purposeRouter)
Router.use("/service",serviceRouter)
Router.use("/team",teamRouter)
Router.use("/user",userRouter)
Router.use("/vision-mission",visionMissionRouter)
Router.use("/ideas",ideasRouter)
Router.use("/bottom",bottomRouter)
Router.use("/partner",partnerRouter)
Router.use("/content-pricing",contentPricingRouter)
Router.use("/top",topRouter)
Router.use("/service-process",serviceProcessRouter)
Router.use("/specialization",specializationRouter)
Router.use("/booking-service",bookingRouter)





 
module.exports = Router